// Mocks generated by Mockito 5.4.4 from annotations
// in sanhour_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sanhour_app/models/offer.dart' as _i5;
import 'package:sanhour_app/models/product.dart' as _i4;
import 'package:sanhour_app/models/shop.dart' as _i3;
import 'package:sanhour_app/providers/shops_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ShopsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopsProvider extends _i1.Mock implements _i2.ShopsProvider {
  MockShopsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Shop> get shops => (super.noSuchMethod(
        Invocation.getter(#shops),
        returnValue: <_i3.Shop>[],
      ) as List<_i3.Shop>);

  @override
  List<_i4.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  List<_i5.Offer> get offers => (super.noSuchMethod(
        Invocation.getter(#offers),
        returnValue: <_i5.Offer>[],
      ) as List<_i5.Offer>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.Shop> get featuredShops => (super.noSuchMethod(
        Invocation.getter(#featuredShops),
        returnValue: <_i3.Shop>[],
      ) as List<_i3.Shop>);

  @override
  List<_i3.Shop> get favoriteShops => (super.noSuchMethod(
        Invocation.getter(#favoriteShops),
        returnValue: <_i3.Shop>[],
      ) as List<_i3.Shop>);

  @override
  List<_i4.Product> get favoriteProducts => (super.noSuchMethod(
        Invocation.getter(#favoriteProducts),
        returnValue: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  List<_i5.Offer> get favoriteOffers => (super.noSuchMethod(
        Invocation.getter(#favoriteOffers),
        returnValue: <_i5.Offer>[],
      ) as List<_i5.Offer>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> fetchShops({
    String? category,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchShops,
          [],
          {
            #category: category,
            #refresh: refresh,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchProducts({
    String? shopId,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
          {
            #shopId: shopId,
            #refresh: refresh,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchOffers({
    String? shopId,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOffers,
          [],
          {
            #shopId: shopId,
            #refresh: refresh,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadShops({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadShops,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadProducts({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadOffers({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadOffers,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void search(String? query) => super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isFavorite(String? shopId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [shopId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> toggleFavorite(
    String? type,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [
            type,
            id,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleShopFavorite(String? shopId) => (super.noSuchMethod(
        Invocation.method(
          #toggleShopFavorite,
          [shopId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleProductFavorite(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleProductFavorite,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleOfferFavorite(String? offerId) => (super.noSuchMethod(
        Invocation.method(
          #toggleOfferFavorite,
          [offerId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
